import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GiveFoodData } from "../components/Context";
import { ProvideOrderData } from "@/components/OrderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvideOrderData>
        <GiveFoodData>
          {children}
        </GiveFoodData>
        </ProvideOrderData>
      </body>
    </html>
  );
}
